// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/EchoCelebrationShareCard.tsx": () => import("../components/mockups/EchoCelebrationShareCard.tsx"),
  "./components/mockups/EchoShareCard.tsx": () => import("../components/mockups/EchoShareCard.tsx"),
  "./components/mockups/WaveCardTitlePreview.tsx": () => import("../components/mockups/WaveCardTitlePreview.tsx"),
  "./components/mockups/atlas/Atlas.tsx": () => import("../components/mockups/atlas/Atlas.tsx")
};
